// Code generated by "stringer -type=SessionStatus -trimprefix=SessionStatus"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SessionStatusUnknown-0]
	_ = x[SessionStatusActive-1]
	_ = x[SessionStatusTimeout-2]
	_ = x[SessionStatusClosed-3]
}

const _SessionStatus_name = "UnknownActiveTimeoutClosed"

var _SessionStatus_index = [...]uint8{0, 7, 13, 20, 26}

func (i SessionStatus) String() string {
	if i < 0 || i >= SessionStatus(len(_SessionStatus_index)-1) {
		return "SessionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionStatus_name[_SessionStatus_index[i]:_SessionStatus_index[i+1]]
}
