// Code generated by "stringer -type=TicketStatus -trimprefix=TicketStatus"; DO NOT EDIT.

package entities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TicketStatusUnknown-0]
	_ = x[TicketStatusWaiting-1]
	_ = x[TicketStatusAdmitted-2]
	_ = x[TicketStatusUsed-3]
	_ = x[TicketStatusExpired-4]
}

const _TicketStatus_name = "UnknownWaitingAdmittedUsedExpired"

var _TicketStatus_index = [...]uint8{0, 7, 14, 22, 26, 33}

func (i TicketStatus) String() string {
	if i < 0 || i >= TicketStatus(len(_TicketStatus_index)-1) {
		return "TicketStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TicketStatus_name[_TicketStatus_index[i]:_TicketStatus_index[i+1]]
}
